[package]
name = "node-testing"
version = "2.0.1"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Test utilities for Substrate node."
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
publish = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
pallet-balances = { version = "2.0.1" }
sc-service = { version = "0.8.1", features = ["test-helpers", "db"] }
sc-client-db = { version = "0.8.1", features = ["kvdb-rocksdb", "parity-db"] }
sc-client-api = { version = "2.0.1" }
codec = { package = "parity-scale-codec", version = "1.3.6" }
pallet-contracts = { version = "2.0.1" }
pallet-grandpa = { version = "2.0.1" }
pallet-indices = { version = "2.0.1" }
sp-keyring = { version = "2.0.1" }
node-executor = { version = "2.0.1", path = "../executor" }
node-primitives = { version = "2.0.1", path = "../primitives" }
node-runtime = { version = "2.0.1", path = "../../../runtime/alphaville" }
sp-core = { version = "2.0.1" }
sp-io = { version = "2.0.1" }
frame-support = { version = "2.0.1" }
pallet-session = { version = "2.0.1" }
pallet-society = { version = "2.0.1" }
sp-runtime = { version = "2.0.1" }
pallet-staking = { version = "2.0.1" }
sc-executor = { version = "0.8.1", features = ["wasmtime"] }
sp-consensus = { version = "0.8.1" }
frame-system = { version = "2.0.1" }
substrate-test-client = { version = "2.0.1", path = "../../../test-utils/client" }
pallet-timestamp = { version = "2.0.1" }
pallet-transaction-payment = { version = "2.0.1" }
pallet-treasury = { version = "2.0.1" }
sp-api = { version = "2.0.1" }
sp-timestamp = { version = "2.0.1", default-features = false }
sp-block-builder = { version = "2.0.1" }
sc-block-builder = { version = "0.8.1" }
sp-inherents = { version = "2.0.1" }
sp-blockchain = { version = "2.0.1" }
log = "0.4.8"
tempfile = "3.1.0"
fs_extra = "1"
futures = "0.3.1"

[dev-dependencies]
criterion = "0.3.0"
sc-cli = { version = "0.8.1" }
